export const KNOWN_NODE_TYPES: Record<string, number[]> = {
  'n8n-nodes-base.webhook': [1, 1.1, 2],
  'n8n-nodes-base.scheduleTrigger': [1, 1.1, 1.2],
  'n8n-nodes-base.manualTrigger': [1],
  'n8n-nodes-base.errorTrigger': [1],
  'n8n-nodes-base.telegramTrigger': [1],
  'n8n-nodes-base.formTrigger': [1, 2],
  'n8n-nodes-base.emailReadImap': [1, 2],
  'n8n-nodes-base.gmail': [2, 2.1],
  'n8n-nodes-base.gmailTrigger': [1, 1.1, 1.2],
  'n8n-nodes-base.code': [1, 2],
  'n8n-nodes-base.if': [1, 2],
  'n8n-nodes-base.switch': [1, 2, 3],
  'n8n-nodes-base.set': [1, 2, 3, 3.4],
  'n8n-nodes-base.merge': [1, 2, 2.1, 3],
  'n8n-nodes-base.splitInBatches': [1, 2, 3],
  'n8n-nodes-base.filter': [1, 2],
  'n8n-nodes-base.removeDuplicates': [1],
  'n8n-nodes-base.httpRequest': [1, 2, 3, 4, 4.1, 4.2],
  'n8n-nodes-base.respondToWebhook': [1, 1.1],
  'n8n-nodes-base.telegram': [1],
  'n8n-nodes-base.emailSend': [1, 2, 2.1],
  'n8n-nodes-base.slack': [1, 2, 2.1, 2.2],
  'n8n-nodes-base.mongoDb': [1],
  'n8n-nodes-base.postgres': [1, 2, 2.3, 2.4, 2.5],
  'n8n-nodes-base.rssFeedRead': [1],
  'n8n-nodes-base.readWriteFile': [1],
  'n8n-nodes-base.dateTime': [1, 2],
  'n8n-nodes-base.crypto': [1],
  'n8n-nodes-base.wait': [1, 1.1],
  'n8n-nodes-base.noOp': [1],
  'n8n-nodes-base.stickyNote': [1],
};

export const TRIGGER_TYPES = new Set([
  'n8n-nodes-base.webhook',
  'n8n-nodes-base.scheduleTrigger',
  'n8n-nodes-base.manualTrigger',
  'n8n-nodes-base.errorTrigger',
  'n8n-nodes-base.telegramTrigger',
  'n8n-nodes-base.emailReadImap',
]);

export const FORBIDDEN_NODE_TYPES = [
  'n8n-nodes-base.executeCommand',
  'n8n-nodes-base.readBinaryFile',
  'n8n-nodes-base.readBinaryFiles',
  'n8n-nodes-base.writeBinaryFile',
  'n8n-nodes-base.readWriteFile',
  'n8n-nodes-base.ssh',
  'n8n-nodes-base.executeSsh',
];
